#!/bin/bash
# rapidget - Downloadmanager for rapidshare
# Author: Alexander Surma <surma@drebesium.org> - released under GPL

# Settings
COOKIEFILE="${HOME}/.rapidget"
LOGINURL="https://ssl.rapidshare.com/cgi-bin/premiumzone.cgi"

REAUTH=""
FILE=""
ACTFILE=""
URL=""
APPNAME=$(basename "${0}")
VERSION=2.1.2

version()
{
	echo "${APPNAME} v${VERSION}"
}

usage()
{
	version
	echo " [OPTIONS] [wget OPTIONS]"
	echo "Options:"
	echo "  -f FILE		Read URLS from FILE"
	echo "  -d URL		Load a single URL"
	echo "  -c PATH 	User this file instead of the default file for cookies (i.e. ~/.rapidget)"
	echo "  -u USER:PASS	Login using this data and save cookie to file"
	echo "  -v		Print version"
	echo "  -h		This message"
	mkill $@
}

cleanup()
{
	[ -n "${ACTFILE}" ] && rm -rf "${ACTFILE}"
}

mkill()
{
	cleanup
	exit ${1-1}
}

error()
{
	echo "${APPNAME}: ${1}" >&2
	mkill ${2} 
}

login()
{
	echo "Logging in..."
	NUM=$(wget -O - --post-data="login=${DATA[0]}&password=${DATA[1]}" \
		--save-cookies="${COOKIEFILE}" "${LOGINURL}" 2>/dev/null  \
		| grep -i 'Settings' \
		| wc -l)
	[ "${NUM}" -le 0 ] && error "Login incorrect"
}

dlfile()
{
	trap mkill INT TERM
	ACTURL="${1}"
	shift
	ACTFILE=$(basename "${ACTURL}")
	wget -O "${ACTFILE}" $@ --load-cookies="${COOKIEFILE}" "${ACTURL}" 

}

trap mkill INT TERM

while getopts ":vhc:u:f:d:" arg; do
	case "${arg}" in
		f) FILE="${OPTARG}" ;;
		d) URL="${OPTARG}" ;;
		c) COOKIEFILE="${OPTARG}" ;;
		u) DATA=($(echo ${OPTARG} | sed 's/:/ /')) ; REAUTH="y" ;;
		v) version ; mkill 0 ;;
		h) usage 0 ;;
		:) error "${OPTARG} requires an argument" ;;
		?) usage 1 ;;
	esac
done
shift $((${OPTIND}-1))
[ -n "${REAUTH}" ] && login
if [ -n "${URL}" ]; then
	ACTFILE=$(basename "${URL}")
	wget -O "${ACTFILE}" $@ --load-cookies="${COOKIEFILE}" "${URL}"
else
	if [ -z "${FILE}" ]; then
		while read LINE; do
			dlfile "${LINE}" $@
		done
	else
		cat "${FILE}" | while read LINE; do
			dlfile "${LINE}" $@
		done
	fi
fi
unset ACTFILE
cleanup
