#!/bin/bash
# rapidget - Downloadmanager for rapidshare
# Author: Alexander Surma <surma@drebesium.org> - released under GPL

# Settings
COOKIEFILE="${HOME}/.rapidget"
LOGINURL="https://ssl.rapidshare.com/cgi-bin/premiumzone.cgi"

REAUTH=""
FILE=""
ACTFILE=""
APPNAME=$(basename "${0}")
VERSION=2.0

version()
{
	echo "${APPNAME} v${VERSION}"
}

usage()
{
	version
	echo " [OPTIONS] <URL> [wget OPTIONS]"
	echo "Options:"
	echo "  -f		URL is a file containing a list of URLs rather than a single URL"
	echo "  -c PATH 	User this file instead of the default file for cookies (i.e. ~/.rapidget)"
	echo "  -u USER:PASS	Login using this data and save cookie to file"
	echo "  -v		Print version"
	echo "  -h		This message"
	mkill $@
}

cleanup()
{
	[ -n "${ACTFILE}" ] && rm -rf "${ACTFILE}"
}

mkill()
{
	cleanup
	exit ${1-1}
}

error()
{
	echo "${APPNAME}: ${1}" >&2
	mkill ${2} 
}

login()
{
	NUM=$(wget -O - --post-data="login=${DATA[0]}&password=${DATA[1]}" \
		--save-cookies="${COOKIEFILE}" "${LOGINURL}" | grep incorrect \
		| wc -l)
	[ "${NUM}" -gt 0 ] && error "Login incorrect"
}

trap mkill INT TERM

while getopts ":vhc:u:f" arg; do
	case "${arg}" in
		f) FILE="y" ;;
		c) COOKIEFILE="${OPTARG}" ;;
		u) DATA=($(echo ${OPTARG} | sed 's/[^\\]:/ /')) ; REAUTH="y" ;;
		v) version ; mkill 0 ;;
		h) usage 0 ;;
		:) error "${OPTARG} requires an argument" ;;
		?) usage 1 ;;
	esac
done
cleanup
[ -n "${REAUTH}" ] && login
